name: falconx
description: A new Flutter package project.
version: 3.8.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  faltool:
    path: ../faltool
  falkit:
    path: ../falkit
  falmodel:
    path: ../falmodel
  falconnect:
    path: ../falconnect
  falstore:
    path: ../falstore

  #PLATFORM: All
  provider: ^6.1.2
  ansicolor: ^2.0.3

  #PLATFORM: Android, iOS, Linux, MacOS
  flutter_local_notifications: ^18.0.1

  #======= Utils ========#
  #PLATFORM: All
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  app_links: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
