name: falstore
description: A new Flutter package project.
version: 1.1.10
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  faltool:
    path: ../faltool


  #PLATFORM: All
  flutter_secure_storage: ^9.2.4
  ansicolor: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0

flutter:
